version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: kanban-postgres
    environment:
      POSTGRES_DB: kanban_db
      POSTGRES_USER: kanban_user
      POSTGRES_PASSWORD: kanban_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kanban_user -d kanban_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: kanban-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

  postgres-test:
    image: postgres:17
    container_name: kanban-postgres-test
    environment:
      POSTGRES_DB: kanban_db_test
      POSTGRES_USER: kanban_user
      POSTGRES_PASSWORD: kanban_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kanban_user -d kanban_db_test"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgweb:
    image: sosedoff/pgweb:latest
    container_name: kanban-pgweb
    environment:
      DATABASE_URL: postgres://kanban_user:kanban_password@postgres:5432/kanban_db?sslmode=disable
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  postgres_test_data:
  pgadmin_data: