# テスト用の設定
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kanban_db
    driver-class-name: org.postgresql.Driver
    username: kanban_user
    password: kanban_password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  h2:
    console:
      enabled: false
  # DevToolsを無効化（テスト環境）
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    com.example.kanban: INFO