# 全環境共通設定
spring:
  application:
    name: kanban-backend
  jpa:
    # Hibernateが自動的にデータベース方言を検出するため、明示的な指定は不要
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8080

# 共通ログ設定
logging:
  level:
    com.example.kanban: INFO
    root: WARN