# 全環境共通設定
spring:
  application:
    name: kanban-backend
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8080

# 共通ログ設定
logging:
  level:
    com.example.kanban: INFO
    root: WARN