name: Backend Lint

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-lint.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-lint.yml'

jobs:
  lint:
    name: Kotlin Lint & Format Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('backend/**/*.gradle*', 'backend/**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x backend/gradlew

    - name: Run Kotlin compiler warnings check
      run: |
        cd backend
        ./gradlew compileKotlin compileTestKotlin --warning-mode all

    - name: Run detekt (Kotlin static analysis)
      run: |
        cd backend
        ./gradlew detekt

    - name: Run ktlint (Kotlin style checker)
      run: |
        cd backend
        ./gradlew ktlintCheck

    - name: Upload detekt reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: detekt-reports
        path: backend/build/reports/detekt/

    - name: Upload ktlint reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: ktlint-reports
        path: backend/build/reports/ktlint/

    - name: Annotate PR with detekt findings
      uses: github/super-linter/slim@v4
      if: github.event_name == 'pull_request'
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_KOTLIN: true
        VALIDATE_ALL_CODEBASE: false